### ISSUE TITLE
Build GitHub stats pages fails since 6/16/2024

### ISSUE THREAD

**Issue by schorschinho** [astrochun/github-stats#7]
Hi @astrochun,

Thanks for writing this great package which has been working flawlessly every day for two years - unfortunately something broke on 6/16, and ever since the deploy fails like this:

```Run astrochun/github-stats-pages@latest
/usr/bin/docker run --name f2ae14ca38a6c0d2e42808b36a14366da0dfa_661701 --label 6f2ae1 --workdir /github/workspace --rm -e "BOT_NAME" -e "BOT_EMAIL" -e "INPUT_USERNAME" -e "INPUT_TOKEN" -e "INPUT_INCLUDE-REPOS" -e "INPUT_EXCLUDE-REPOS" -e "INPUT_TEST" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/github-stats-osprey/github-stats-osprey":"/github/workspace" 6f2ae1:4ca38a6c0d2e42808b36a14366da0dfa  "schorschinho" "***" "osprey" "" ""
Traceback (most recent call last):
  File "/usr/local/bin/get_repo_list", line 5, in <module>
    from github_stats_pages import repo_list, __version__
  File "/github_stats_pages/repo_list.py", line 4, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.[9](https://github.com/schorschinho/github-stats-osprey/actions/runs/10155492050/job/28082345867#step:6:10)/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Traceback (most recent call last):
  File "/usr/local/bin/gts_run_all_repos", line 5, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Do you have an idea of what I might try to fix it?

Thanks,
Georg

**Comment by astrochun** [comment]
Hi,

Glad to hear that you find it useful. I think what happened was that there were some breaking changes to pandas and numpy. I'm not sure when I can get this fixed, but will try soon. If you want, you can submit a PR to bump numpy above v2 and pandas above v2. I think that will resolve this issue with the C compiler.
